---
# tasks file for roles/systemd/service
- name: Build required folders
  file: state=directory path="{{ item }}" recurse=yes
  with_items:
    - "{{ ansible_unit_test_prefix_dir }}{{ systemd_service_default_dir }}"
    - "{{ ansible_unit_test_prefix_dir }}{{ systemd_service_systemd_dir }}"

- name: Add default environment variables file
  template: src="default.j2" dest="{{ ansible_unit_test_prefix_dir }}/{{ systemd_service_default_dir }}/{{ systemd_service_name }}"
  notify: reload systemd service

- name: Add sytemd service file
  template: src="service.j2" dest="{{ ansible_unit_test_prefix_dir }}/{{ systemd_service_systemd_dir }}/{{ systemd_service_name }}.service"
  register: service_file
  notify:
    - reload systemd daemon
    - reload systemd service
