---
# handlers file for roles/systemd/service
- name: reload systemd service
  systemd:
    name: '{{ systemd_service_name }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: not ansible_unit_test
