---
# handlers file for roles/systemd/service
- name: reload systemd service
  service:
    name: '{{ systemd_service_name }}'
    state: restarted
  when: not ansible_unit_test

- name: reload systemd daemon
  shell: systemctl daemon-reload
  when: ansible_unit_test
  tags:
    - skip_ansible_lint
